# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/askee/kraya/ExerciceOumayma

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/askee/kraya/ExerciceOumayma

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/askee/kraya/ExerciceOumayma/CMakeFiles /home/askee/kraya/ExerciceOumayma/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/askee/kraya/ExerciceOumayma/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named etudiant

# Build rule for target.
etudiant: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 etudiant
.PHONY : etudiant

# fast build rule for target.
etudiant/fast:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/build
.PHONY : etudiant/fast

Etudiant.o: Etudiant.cpp.o

.PHONY : Etudiant.o

# target to build an object file
Etudiant.cpp.o:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/Etudiant.cpp.o
.PHONY : Etudiant.cpp.o

Etudiant.i: Etudiant.cpp.i

.PHONY : Etudiant.i

# target to preprocess a source file
Etudiant.cpp.i:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/Etudiant.cpp.i
.PHONY : Etudiant.cpp.i

Etudiant.s: Etudiant.cpp.s

.PHONY : Etudiant.s

# target to generate assembly for a file
Etudiant.cpp.s:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/Etudiant.cpp.s
.PHONY : Etudiant.cpp.s

filiere.o: filiere.cpp.o

.PHONY : filiere.o

# target to build an object file
filiere.cpp.o:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/filiere.cpp.o
.PHONY : filiere.cpp.o

filiere.i: filiere.cpp.i

.PHONY : filiere.i

# target to preprocess a source file
filiere.cpp.i:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/filiere.cpp.i
.PHONY : filiere.cpp.i

filiere.s: filiere.cpp.s

.PHONY : filiere.s

# target to generate assembly for a file
filiere.cpp.s:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/filiere.cpp.s
.PHONY : filiere.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/main.cpp.s
.PHONY : main.cpp.s

matiere.o: matiere.cpp.o

.PHONY : matiere.o

# target to build an object file
matiere.cpp.o:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/matiere.cpp.o
.PHONY : matiere.cpp.o

matiere.i: matiere.cpp.i

.PHONY : matiere.i

# target to preprocess a source file
matiere.cpp.i:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/matiere.cpp.i
.PHONY : matiere.cpp.i

matiere.s: matiere.cpp.s

.PHONY : matiere.s

# target to generate assembly for a file
matiere.cpp.s:
	$(MAKE) -f CMakeFiles/etudiant.dir/build.make CMakeFiles/etudiant.dir/matiere.cpp.s
.PHONY : matiere.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... etudiant"
	@echo "... Etudiant.o"
	@echo "... Etudiant.i"
	@echo "... Etudiant.s"
	@echo "... filiere.o"
	@echo "... filiere.i"
	@echo "... filiere.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... matiere.o"
	@echo "... matiere.i"
	@echo "... matiere.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

